### GET (Basic)
http://localhost:5000

### GET (ALL)
http://localhost:5000/api/dishes

### GET (by ID)
http://localhost:5000/api/dishes/10

### GET (recipes by dish)
http://localhost:5000/api/dishes/3/recipes

### POST
POST http://localhost:5000/api/dishes HTTP/1.1
content-type: application/json

{
  "name": "Test User",
  "cohort_id": 1 
}

### PUT
PUT http://localhost:5000/api/dishes/10 HTTP/1.1
content-type: application/json

{
  "name": "Sam",
  "cohort_id": 4 
}

### DELETE
DELETE http://localhost:5000/api/dishes/11

